version: "3"
services:
  v8-api:
    container_name: v8-api
    restart: always
    build: .
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file: .env
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
      - "9229:9229" # debugging port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      FORCE_COLOR: "true"
    links:
      - v8-db
    depends_on:
      - v8-db
    networks:
      - v8-network
  v8-db:
    container_name: v8-db
    image: mongo
    restart: always
    command: mongod --port ${MONGO_PORT}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "$MONGO_PORT:$MONGO_PORT"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - v8-network

networks:
  v8-network:
    driver: bridge
    external: true
