version: "3.7"

services:
  rpg-api:
    image: definya/definya-team:api-latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SOCKET_PORT}:${SOCKET_PORT}"
    environment:
      FORCE_COLOR: "true"
      CHOKIDAR_USEPOLLING: "true"
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "Definya API"
    networks:
      - rpg-network
    configs:
      - source: rpg-env
        target: .env
    env_file:
      - .env
    labels:
      # Basic setup
      - traefik.enable=true
      - traefik.http.routers.rpg-api.rule=Host(`temp-na.definya.com`)
      - traefik.http.routers.rpg-api.entrypoints=websecure
      - traefik.http.routers.rpg-api.tls.certresolver=myresolver
      - traefik.http.services.rpg-api.loadbalancer.server.port=${SERVER_PORT}
      # WebSocket specific routing
      - traefik.http.routers.rpg-api-socket.rule=Host(`temp-na.definya.com`) && Path(`/socket.io/`)
      - traefik.http.routers.rpg-api-socket.entrypoints=websecure
      - traefik.http.routers.rpg-api-socket.tls.certresolver=myresolver
      - traefik.http.middlewares.rpg-api-socket-headers.headers.customrequestheaders.X-Forwarded-For=$proxy_add_x_forwarded_for
      - traefik.http.middlewares.rpg-api-socket-headers.headers.customrequestheaders.Upgrade=$http_upgrade
      - traefik.http.middlewares.rpg-api-socket-headers.headers.customrequestheaders.Connection=upgrade
      - traefik.http.routers.rpg-api-socket.middlewares=rpg-api-socket-headers

  rpg-db:
    image: mongo
    command: mongod --port ${MONGO_PORT}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - rpg-db-data:/data/db
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    deploy: # db should be only on the manager node
      placement:
        constraints:
          - node.role == manager
    networks:
      - rpg-network
    configs:
      - source: rpg-env
        target: .env
    env_file:
      - .env

  rpg-redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - rpg-redis-data:/data
      - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf", "--port", "${REDIS_PORT}"]
    networks:
      - rpg-network
    configs:
      - source: rpg-env
        target: .env
    env_file:
      - .env

  traefik:
    image: traefik:v2.4
    command:
      # Basic setup
      - --api.insecure=true
      - "--api.dashboard=true"
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Setup SSL
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=admin@definya.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - --accesslog=true
      - --accesslog.filepath=./traeffik-logfile.log
      - --tracing.jaeger=true
    ports:
      - "80:80"
      - "443:443"
      - "5003:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt

    networks:
      - rpg-network

networks:
  rpg-network:
    driver: overlay

configs:
  rpg-env:
    file: .env

volumes:
  rpg-db-data:
  rpg-redis-data:
