version: "3"

services:
  laundry-api:
    container_name: laundry-api
    restart: always
    build: .
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - laundy-db
      - laundry-redis
    depends_on:
      - laundy-db
      - laundry-redis
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "$SOCKET_PORT:$SOCKET_PORT"
      # - "$SOCKET_UDP_RANGE" #!COMMENT THIS IN IF USING UDP
    environment:
      FORCE_COLOR: "true"
      VIRTUAL_HOST: ${API_SUBDOMAIN}
      LETSENCRYPT_HOST: ${API_SUBDOMAIN}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
      VIRTUAL_PORT: ${SERVER_PORT}
      CHOKIDAR_USEPOLLING: "true" # enables hot-reloading on windows host
      NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
      NEW_RELIC_APP_NAME: "Laundrobot.AI API"
    networks:
      - laundry-network

  laundy-db:
    container_name: laundy-db
    image: mongo
    restart: always
    command: mongod --port ${MONGO_PORT}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "$MONGO_PORT:$MONGO_PORT"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - laundry-network

  laundry-redis:
    container_name: laundry-redis
    restart: always
    image: redis:latest
    ports:
      - "$REDIS_PORT:$REDIS_PORT"
    expose:
      - "$REDIS_PORT"
    env_file: .env
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf", "--port", "${REDIS_PORT}"]
    networks:
      - laundry-network

networks:
  laundry-network:
    external: true
