name: Code Review (ChatGPT)

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened]
    branches: ["master"]

jobs:
  check-chatgpt-review-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for chatgpt-review label
        if: contains(github.event.pull_request.labels.*.name, 'chatgpt-review')
        run: echo "chatgpt-review label found on pull request #${{ github.event.number }}"
      - name: Skip if no chatgpt-review label
        if: contains(github.event.pull_request.labels.*.name, 'chatgpt-review') == false
        run: echo "chatgpt-review label not found on pull request #${{ github.event.number }}; skipping workflow"
        continue-on-error: true

  chatgpt-pr-review:
    needs: check-chatgpt-review-label
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
