name: Code Review (ChatGPT)

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [labeled]

jobs:
  chatgpt-pr-review:
    if: ${{ github.event.label.name == 'chatgpt-review' }}
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
